# A~~!

version: 1.0.2

lobby-location:
  world: world
  x: 112.51868078229245
  y: 201.0
  z: -34.49331185200908
  yaw: -179.99902
  pitch: -1.059041

teleport-on-first-join: true

gui-title: §8伺服器選擇菜單

menu-item:
  enabled: true
  material: COMPASS
  name: §b§l伺服器傳送指南針
  lore:
  - §7右鍵點擊開啟伺服器選單
  slot: 4

teleport-options:
  survival:
    item: GRASS_BLOCK
    name: §a§l生存世界
    lore:
    - §7點擊傳送到生存世界&6[&b/rtp&6]。
    command: rtp
    slot: 11
  
  skyblock:
    item: GRASS_BLOCK
    name: §c§lLobby
    lore:
    - §7點擊傳送到空島模式。
    command: lobby
    slot: 13
